fix(minor): Fixed bug in Windows with incorrect slashes in paths
FatehAK/vite-plugin-image-optimizer pull request #14
Opened 2023-03-11 18:21 UTC by NecroMan

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation
- [ ] Other

### Description

In Windows paths in `publicDir` is incorrect, so no images can be found to optimize.
Checked in Windows but didn't check in Linux/MacOS but should work :)

### Checks

- [ ] PR adheres to the code style of this project
- [ ] Related issues linked using `fixes #number`
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Lint and build have passed locally by running `pnpm lint && pnpm build`
- [x] Code changes have been verified in local
- [ ] Documentation added/updated if necessary

### Additional Context

2023-03-11 20:31 UTC, FatehAK requested changes
Can you make this change at line 126 instead? That way we don't have to reassign `publicDir` again and makes the change consistent across the file.

Also noticed a typo in the comment <strike>'stile'</strike> to 'style'

Like this,
```js
if (typeof c.publicDir === 'string') {
	// normalize slashes in publicDir to Linux style
    publicDir = c.publicDir.replace(/[/\\]/g, '/');
}
```

2023-03-11 20:34 UTC, FatehAK commented
Thanks for contribution! Please review the changes requested.

2023-03-12 09:27 UTC, NecroMan commented
Done!

2023-03-12 09:54 UTC, merged

2023-03-12 10:06 UTC, FatehAK commented
Just released v1.1.2 with the fix. Thanks again!