fix: import libraries instead of require
FatehAK/vite-plugin-image-optimizer pull request #5
Opened 2022-12-30 17:34 UTC by mfjordvald

The require() calls trigger an exception `ReferenceError: require is not defined`
This fixes this by using import instead of require.

To be entirely honest, I'm not sure if there are potential side effects in doing this, but it seems to be a common issue, as seen at: https://github.com/vitejs/vite/issues/3409

None of the suggested solutions there worked, though.

2022-12-31 11:34 UTC, FatehAK commented
That's weird that shouldn't happen. The reason why I have used `require` is to let the users choose whether they want to use sharp or svgo or both. That's why the requires are kept within the function blocks instead of top level. 

If we keep the imports at the top level then we lose that flexibility and users would have to install both sharp and svgo.

I'm using the package in some of my repo's, I didn't face any issue with requires there.
https://github.com/FatehAK/navigo-app
https://github.com/FatehAK/memrise

Could you check and compare with your repo or provide a minimal repro for me to check?

2023-01-01 09:57 UTC, mfjordvald commented
Okay I've finally figured out the root cause. Had a ton of twist and turns to understand deeply what was going on but in the end it was as simple as the vite config file being named `vite.config.mjs`.  This indicated that the vite config file was a ES6 module file and therefore it loaded the `index.mjs` file of this plugin, which does not allow CommonJS require().

Supposedly you can enable `transformMixedEsModules` in `commonjsOptions` but even this, for some reason, didn't work.

So there are a few options before closing/resolving this PR. 

1. I believe you can simply remove the `module` filename in `package.json` to only build the common JS file file and not the module JS file.
2. It could be explicitly mentioned in the config that `.mjs` vite config is not supported, though this seems not optimal. 
3. Use dynamic import to keep the conditional loading, but still remove the require calls. I've adapted the PR for this already if you want to test it out.

During my research into what was going on I also found the maintainer of Rollup mentioning mixing es6 and cjs as a bad practice: https://github.com/rollup/plugins/issues/518#issuecomment-666133709

Which is why I ended up with the dynamic import solution rather than simply renaming my vite config file. (As I also don't know what the potential side-effects of that might be)

2023-01-01 10:28 UTC, FatehAK requested changes
We have to add 'svgo' and 'sharp' as externals else their code is bundled as well. 

`external: ['fs', 'fs/promises', 'svgo', 'sharp'],`

and then in output we have to define them as globals

```js
output: {
          globals: {
            fs: 'fs',
            'fs/promises': 'fsp',
            'svgo': 'svgo',
            'sharp': 'sharp',
          },
        },
```

2023-01-01 10:28 UTC, FatehAK commented
Ah no wonder! Thanks for taking the time to figure it out made me understand as well 😄. The dynamic import option looks good I should have went with it from the start my bad. 

I just tested it out works well with .mjs and .js vite configs, there was just an issue with vite/rollup bundling `svgo` and `sharp` in the final bundle as well. We have to mark them as external seems like and put them in the globals definition.

2023-01-01 10:43 UTC, merged

2023-01-01 10:45 UTC, FatehAK commented
Merged it, thanks for the suggesting the fix 👍 . Will make a release shortly

2023-01-01 10:49 UTC, FatehAK commented
Please update to v1.0.6 it has the fixes